"""The review workbook. Same colour language as the existing tools: GREEN header = you edit it, YELLOW cell = unconfirmed,
ORANGE row = deferred, RED = overdue. Rodney edits the green columns; import_decisions reads them back."""
from __future__ import annotations

import sqlite3
from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

from .. import db

GREEN = PatternFill("solid", fgColor="C6EFCE")
GREY = PatternFill("solid", fgColor="D9D9D9")
YELLOW = PatternFill("solid", fgColor="FFF2CC")
ORANGE = PatternFill("solid", fgColor="F8CBAD")
RED = Font(color="C00000", bold=True)
BOLD = Font(bold=True)
AP_STATUSES = ["Unpaid", "Scheduled", "Partially Paid", "Paid", "Deferred (no-breach)", "Disputed", "On Hold", "Void-Credit", "Reference only"]
AR_STATUSES = ["Open", "Paid", "Partially Paid", "Doubtful", "Estimate"]


def _header(ws, cols: list[tuple[str, bool]], widths: dict[int, int] | None = None):
    for i, (name, editable) in enumerate(cols, 1):
        c = ws.cell(row=1, column=i, value=name)
        c.font = BOLD
        c.fill = GREEN if editable else GREY
        c.alignment = Alignment(wrap_text=True, vertical="top")
    ws.freeze_panes = "A2"
    for i, _ in enumerate(cols, 1):
        ws.column_dimensions[get_column_letter(i)].width = (widths or {}).get(i, 16)


def export_workbook(conn: sqlite3.Connection, settings, fc, report: dict, path: str | Path) -> Path:
    wb = Workbook()
    ws = wb.active
    ws.title = "DASHBOARD"
    rows = [
        ("RAM EXCAVATING LIMITED - WEEKLY REVIEW WORKBOOK", ""), (f"As of {report['as_of']}", "generated by ramfin; edit only GREEN-headed columns on the other tabs"),
        ("", ""), ("HEADLINE", report["headline"]), ("", ""),
        ("Cash in bank", report["cash"]), ("Operating line drawn", report["loc_drawn"]), ("Line limit", report["loc_limit"]), ("LOC headroom", report["headroom"]),
        ("Position (cash minus line)", report["position"]), (f"Lowest week ({report['basis']} basis)", report["lowest"]), ("Breach weeks", report["breach_weeks"]), ("", ""),
        ("Open AR", report["open_ar"]), ("Estimated billings in forecast", report["estimated_ar"]), ("Doubtful AR", report["doubtful_ar"]),
        ("AR concentration (top 2)", report["ar_concentration"]), ("Holdback receivable", report["holdback_receivable"]), ("", ""),
        ("Open AP (register)", report["open_ap"]), ("Unconfirmed AP", report["unconfirmed_ap"]), ("AP with NO pay date (invisible)", report["no_date_ap"]),
        ("Overdue AP", report["overdue_ap"]), ("", ""),
        ("Receipt capture rate (90d)", report["capture_rate"] if report["capture_rate"] is not None else "n/a"),
        ("Actions: today / week / later", f"{report['actions_today']} / {report['actions_week']} / {report['actions_later']}"),
    ]
    for r in rows:
        ws.append(list(r))
    ws.column_dimensions["A"].width = 38
    ws.column_dimensions["B"].width = 90
    for r in range(6, 24):
        ws.cell(row=r, column=2).number_format = '#,##0.00'
    ws.cell(row=17, column=2).number_format = '0%'
    if report["deferrals"]:
        ws.append(["", ""]); ws.append(["DEFERRED AP - ACTION REQUIRED", ""])
        for d in report["deferrals"]:
            ws.append([d["label"], f"${d['amount']:,.2f}: {d['from_date']} -> {d['to_date']}. {d['reason']}"])
            ws.cell(row=ws.max_row, column=1).fill = ORANGE
    if report["warnings"]:
        ws.append(["", ""]); ws.append(["DATA QUALITY", ""])
        for w in report["warnings"]:
            ws.append(["", w])

    # FORECAST
    ws = wb.create_sheet("FORECAST_13WK")
    _header(ws, [("Week start", False), ("Week end", False), ("Opening", False), ("Inflows", False), ("Outflows", False), ("Closing", False), ("Status", False), ("Lines", False)], {8: 90})
    for w in fc.weeks:
        ws.append([w.start, w.end, round(w.opening, 2), round(w.inflows, 2), round(w.outflows, 2), round(w.closing, 2), w.status,
                   "; ".join(f"{ln.label} {ln.amount:+,.0f}" for ln in sorted(w.lines, key=lambda x: x.amount))])
        if w.status == "BREACH":
            ws.cell(row=ws.max_row, column=7).font = RED
        elif w.status == "TIGHT":
            ws.cell(row=ws.max_row, column=7).fill = YELLOW
    for r in range(2, ws.max_row + 1):
        for c in (3, 4, 5, 6):
            ws.cell(row=r, column=c).number_format = '#,##0'

    # AP_TRACKER
    ws = wb.create_sheet("AP_TRACKER")
    _header(ws, [("ID", False), ("Vendor", False), ("Invoice #", False), ("Invoice date", False), ("Due date", False), ("Amount", True), ("Amt Confirmed", True),
                 ("Payment Status", True), ("Planned Pay Date", True), ("Date Paid", True), ("Method", True), ("Job", True), ("Cost Code", True), ("Category", False), ("Notes", True)],
            {2: 28, 15: 40})
    dv_status = DataValidation(type="list", formula1='"' + ",".join(AP_STATUSES) + '"', allow_blank=True)
    dv_yn = DataValidation(type="list", formula1='"Yes,No"', allow_blank=True)
    ws.add_data_validation(dv_status); ws.add_data_validation(dv_yn)
    today = date.today().isoformat()
    for p in db.rows(conn, "SELECT a.*, v.name vname FROM ap_invoices a LEFT JOIN vendors v ON v.id=a.vendor_id "
                           "WHERE a.status<>'Paid' OR a.paid_date >= date('now','-45 days') ORDER BY a.status='Paid', a.planned_pay_date"):
        ws.append([p["id"], p["vname"], p["invoice_no"], p["invoice_date"], p["due_date"], p["amount"], "Yes" if p["amount_confirmed"] else "No", p["status"],
                   p["planned_pay_date"], p["paid_date"], p["method"], p["job_no"], p["cost_code"], p["category"], p["notes"]])
        r = ws.max_row
        dv_status.add(ws.cell(row=r, column=8)); dv_yn.add(ws.cell(row=r, column=7))
        ws.cell(row=r, column=6).number_format = '#,##0.00'
        if not p["amount_confirmed"] or p["amount"] is None:
            ws.cell(row=r, column=6).fill = YELLOW
        if p["status"] == "Deferred (no-breach)":
            for c in range(1, 16):
                ws.cell(row=r, column=c).fill = ORANGE
        if p["status"] in ("Unpaid", "Scheduled", "Partially Paid") and p["due_date"] and p["due_date"] < today:
            ws.cell(row=r, column=5).font = RED
        if p["status"] in ("Unpaid", "Scheduled", "Partially Paid") and not p["planned_pay_date"]:
            ws.cell(row=r, column=9).fill = YELLOW

    # AR_TRACKER
    ws = wb.create_sheet("AR_TRACKER")
    _header(ws, [("ID", False), ("Customer", False), ("Invoice #", False), ("Invoice date", False), ("Due date", False), ("Amount", True), ("Paid", False),
                 ("Holdback", False), ("Status", True), ("Expected Date", True), ("Date Paid", True), ("Job", True), ("Notes", True)], {2: 28, 13: 40})
    dv_ar = DataValidation(type="list", formula1='"' + ",".join(AR_STATUSES) + '"', allow_blank=True)
    ws.add_data_validation(dv_ar)
    for a in db.rows(conn, "SELECT * FROM ar_invoices WHERE status<>'Paid' OR paid_date >= date('now','-45 days') ORDER BY status='Paid', expected_date"):
        ws.append([a["id"], a["customer"], a["invoice_no"], a["invoice_date"], a["due_date"], a["amount"], a["paid_amount"], a["holdback"], a["status"],
                   a["expected_date"], a["paid_date"], a["job_no"], a["notes"]])
        r = ws.max_row
        dv_ar.add(ws.cell(row=r, column=9))
        if a["status"] == "Estimate":
            ws.cell(row=r, column=6).fill = YELLOW
        if a["status"] == "Doubtful":
            ws.cell(row=r, column=9).font = RED

    # RECEIPTS
    ws = wb.create_sheet("RECEIPTS")
    _header(ws, [("ID", False), ("Date", False), ("Vendor", False), ("Amount", True), ("GST", False), ("Method", False), ("Job", True), ("Cost Code", True),
                 ("Equipment", True), ("Reimbursable", True), ("Reimbursed", True), ("Matched to bank", False), ("Description", False), ("File", False)], {3: 26, 13: 40, 14: 60})
    ws.add_data_validation(dv_yn2 := DataValidation(type="list", formula1='"Yes,No"', allow_blank=True))
    for rc in db.rows(conn, "SELECT r.*, v.name vname, d.filed_path FROM receipts r LEFT JOIN vendors v ON v.id=r.vendor_id LEFT JOIN documents d ON d.id=r.document_id "
                            "ORDER BY r.receipt_date DESC LIMIT 2000"):
        ws.append([rc["id"], rc["receipt_date"], rc["vname"], rc["amount"], rc["gst"], rc["payment_method"], rc["job_no"], rc["cost_code"], rc["equipment_id"],
                   "Yes" if rc["reimbursable"] else "No", "Yes" if rc["reimbursed"] else "No", "Yes" if rc["matched_txn_id"] else "", rc["description"], rc["filed_path"]])
        r = ws.max_row
        dv_yn2.add(ws.cell(row=r, column=10)); dv_yn2.add(ws.cell(row=r, column=11))
        if not rc["job_no"]:
            ws.cell(row=r, column=7).fill = YELLOW
        if not rc["cost_code"]:
            ws.cell(row=r, column=8).fill = YELLOW
        if rc["amount"] is None:
            ws.cell(row=r, column=4).fill = YELLOW
        if rc["reimbursable"] and not rc["reimbursed"]:
            for c in range(1, 15):
                ws.cell(row=r, column=c).fill = ORANGE

    # MISSING RECEIPTS
    ws = wb.create_sheet("MISSING_RECEIPTS")
    _header(ws, [("Txn ID", False), ("Account", False), ("Date", False), ("Description", False), ("Amount", False), ("Personal / no receipt needed", True)], {4: 50})
    for t in db.rows(conn, "SELECT * FROM bank_transactions WHERE amount<0 AND receipt_required=1 AND (match_type IS NULL OR match_type='none') ORDER BY txn_date DESC LIMIT 1000"):
        ws.append([t["id"], t["account_key"], t["txn_date"], t["description"], -t["amount"], ""])
        ws.cell(row=ws.max_row, column=4).font = RED

    # JOB_COST
    ws = wb.create_sheet("JOB_COST")
    _header(ws, [("Job", False), ("Name", False), ("Labour (loaded)", False), ("Labour hrs", False), ("Receipts", False), ("Invoices", False), ("Total cost", False),
                 ("Billed", False), ("Margin to date", False), ("By cost code", False)], {10: 80})
    for j, v in sorted(report["job_cost"].items(), key=lambda kv: -kv[1]["total"]):
        ws.append([j, v["name"], v["labour"], v["labour_hours"], v["receipts"], v["invoices"], v["total"], v["billed"], v["margin_to_date"],
                   "; ".join(f"{k}: {x:,.0f}" for k, x in sorted(v["by_code"].items(), key=lambda kv: -kv[1]))])

    # EQUIPMENT
    ws = wb.create_sheet("EQUIPMENT")
    _header(ws, [("Unit", False), ("Description", True), ("Repairs", False), ("Fuel", False), ("Other", False), ("Total", False), ("Hours", False), ("$/hr", False), ("Documents", False)], {2: 30})
    for u, v in sorted(report.get("equipment_cost", {}).items(), key=lambda kv: -kv[1]["total"]):
        ws.append([u, v["description"], v["repairs"], v["fuel"], v["other"], v["total"], v["hours"], v["cost_per_hour"], v["documents"]])

    # TIMESHEETS
    ws = wb.create_sheet("TIMESHEETS")
    _header(ws, [("ID", False), ("Employee", False), ("Period end", False), ("Hours", False), ("OT", False), ("Status", True), ("File", False)], {7: 60})
    for t in db.rows(conn, "SELECT t.*, e.name FROM timesheets t JOIN employees e ON e.id=t.employee_id ORDER BY t.period_end DESC LIMIT 200"):
        ws.append([t["id"], t["name"], t["period_end"], t["total_hours"], t["total_ot_hours"], t["status"], t["filed_path"]])

    # ACTIONS
    ws = wb.create_sheet("ACTIONS")
    _header(ws, [("ID", False), ("Priority", False), ("Kind", False), ("What", False), ("Detail", False), ("Status", True), ("Your answer", True)], {4: 60, 5: 70, 7: 40})
    dv_act = DataValidation(type="list", formula1='"open,resolved,dismissed"', allow_blank=True)
    ws.add_data_validation(dv_act)
    for it in db.rows(conn, "SELECT * FROM action_items WHERE status='open' ORDER BY priority, created_at"):
        ws.append([it["id"], {1: "TODAY", 2: "THIS WEEK", 3: "LATER"}[it["priority"]], it["kind"], it["title"], it["detail"], it["status"], ""])
        dv_act.add(ws.cell(row=ws.max_row, column=6))
        if it["priority"] == 1:
            ws.cell(row=ws.max_row, column=2).font = RED

    # README
    ws = wb.create_sheet("README")
    for line in [
        "RAM EXCAVATING LIMITED - WEEKLY REVIEW WORKBOOK (generated by ramfin)",
        "This file is an OUTPUT of the finance database, regenerated every run. Do not add rows; do not rename tabs.",
        "GREEN-headed columns are yours to edit. Everything else is overwritten next run.",
        "YELLOW cell = unconfirmed or missing (fill it in). ORANGE row = deferred under the no-breach rule, or an employee owed money. RED = overdue or missing receipt.",
        "What gets read back in: AP_TRACKER Amount / Amt Confirmed / Payment Status / Planned Pay Date / Date Paid / Method / Job / Cost Code / Notes;",
        "AR_TRACKER Amount / Status / Expected Date / Date Paid / Job / Notes; RECEIPTS Amount / Job / Cost Code / Equipment / Reimbursable / Reimbursed;",
        "MISSING_RECEIPTS 'Personal / no receipt needed' (type Yes); TIMESHEETS Status; ACTIONS Status and Your answer.",
        "Save it in the same place with the same name. The next run picks up your edits, then rewrites the file.",
    ]:
        ws.append([line])
    ws.column_dimensions["A"].width = 140

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    wb.save(p)
    return p
